name: task
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: run setup
        run: make setup
      - name: run tests
        run: make test
      - name: run linter
        run: make lint
